package com.medical.dao;

import com.medical.model.JzAct;
import com.medical.model.JzActExample;
import java.util.List;

public interface JzActDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	int countByExample(JzActExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	int deleteByExample(JzActExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	int deleteByPrimaryKey(Integer actId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	Integer insert(JzAct record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	Integer insertSelective(JzAct record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	List<JzAct> selectByExample(JzActExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	JzAct selectByPrimaryKey(Integer actId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	int updateByExampleSelective(JzAct record, JzActExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	int updateByExample(JzAct record, JzActExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	int updateByPrimaryKeySelective(JzAct record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	int updateByPrimaryKey(JzAct record);
}
