package com.medical.dao;

import com.medical.model.JzChronicapprove;
import com.medical.model.JzChronicapproveExample;
import java.math.BigDecimal;
import java.util.List;

public interface JzChronicapproveDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Tue Jul 02 14:28:11 CST 2013
	 */
	int countByExample(JzChronicapproveExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Tue Jul 02 14:28:11 CST 2013
	 */
	int deleteByExample(JzChronicapproveExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Tue Jul 02 14:28:11 CST 2013
	 */
	int deleteByPrimaryKey(BigDecimal chronicapproveId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Tue Jul 02 14:28:11 CST 2013
	 */
	BigDecimal insert(JzChronicapprove record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Tue Jul 02 14:28:11 CST 2013
	 */
	BigDecimal insertSelective(JzChronicapprove record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Tue Jul 02 14:28:11 CST 2013
	 */
	List<JzChronicapprove> selectByExample(JzChronicapproveExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Tue Jul 02 14:28:11 CST 2013
	 */
	JzChronicapprove selectByPrimaryKey(BigDecimal chronicapproveId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Tue Jul 02 14:28:11 CST 2013
	 */
	int updateByExampleSelective(JzChronicapprove record,
			JzChronicapproveExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Tue Jul 02 14:28:11 CST 2013
	 */
	int updateByExample(JzChronicapprove record, JzChronicapproveExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Tue Jul 02 14:28:11 CST 2013
	 */
	int updateByPrimaryKeySelective(JzChronicapprove record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Tue Jul 02 14:28:11 CST 2013
	 */
	int updateByPrimaryKey(JzChronicapprove record);

	List<JzChronicapprove> selectByExample(JzChronicapproveExample example,int skipResults, int maxResults);
}