package com.medical.dao;

import com.medical.model.JzChronicstatus;
import com.medical.model.JzChronicstatusExample;
import java.util.List;

public interface JzChronicstatusDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICSTATUS
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	int countByExample(JzChronicstatusExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICSTATUS
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	int deleteByExample(JzChronicstatusExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICSTATUS
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	int deleteByPrimaryKey(Long chronicstatusId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICSTATUS
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	Long insert(JzChronicstatus record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICSTATUS
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	Long insertSelective(JzChronicstatus record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICSTATUS
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	List<JzChronicstatus> selectByExample(JzChronicstatusExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICSTATUS
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	JzChronicstatus selectByPrimaryKey(Long chronicstatusId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICSTATUS
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	int updateByExampleSelective(JzChronicstatus record,
			JzChronicstatusExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICSTATUS
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	int updateByExample(JzChronicstatus record, JzChronicstatusExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICSTATUS
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	int updateByPrimaryKeySelective(JzChronicstatus record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICSTATUS
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	int updateByPrimaryKey(JzChronicstatus record);

	List<JzChronicstatus> selectByExample(JzChronicstatusExample example,
			int start, int pagesize);
}