package com.medical.model;

import java.math.BigDecimal;

public class JzAct {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.ACT_ID
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	private Integer actId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.MEMBER_ID
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	private String memberId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.HOSPITAL_ID
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	private String hospitalId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.CENTER_ID
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	private String centerId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.ACT_YEAR
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	private Short actYear;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.ACT_BIZ_TYPE
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	private String actBizType;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.ACT_BIZ_TIMES
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	private Short actBizTimes;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.ACT_BIZ_MONEY
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	private BigDecimal actBizMoney;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.ACT_BIZ_INHOSPITAL_TIMES
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	private Short actBizInhospitalTimes;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.ACT_ID
	 * @return  the value of YLJZN.JZ_ACT.ACT_ID
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	public Integer getActId() {
		return actId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.ACT_ID
	 * @param actId  the value for YLJZN.JZ_ACT.ACT_ID
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	public void setActId(Integer actId) {
		this.actId = actId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.MEMBER_ID
	 * @return  the value of YLJZN.JZ_ACT.MEMBER_ID
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	public String getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.MEMBER_ID
	 * @param memberId  the value for YLJZN.JZ_ACT.MEMBER_ID
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.HOSPITAL_ID
	 * @return  the value of YLJZN.JZ_ACT.HOSPITAL_ID
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	public String getHospitalId() {
		return hospitalId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.HOSPITAL_ID
	 * @param hospitalId  the value for YLJZN.JZ_ACT.HOSPITAL_ID
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	public void setHospitalId(String hospitalId) {
		this.hospitalId = hospitalId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.CENTER_ID
	 * @return  the value of YLJZN.JZ_ACT.CENTER_ID
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	public String getCenterId() {
		return centerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.CENTER_ID
	 * @param centerId  the value for YLJZN.JZ_ACT.CENTER_ID
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	public void setCenterId(String centerId) {
		this.centerId = centerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.ACT_YEAR
	 * @return  the value of YLJZN.JZ_ACT.ACT_YEAR
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	public Short getActYear() {
		return actYear;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.ACT_YEAR
	 * @param actYear  the value for YLJZN.JZ_ACT.ACT_YEAR
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	public void setActYear(Short actYear) {
		this.actYear = actYear;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.ACT_BIZ_TYPE
	 * @return  the value of YLJZN.JZ_ACT.ACT_BIZ_TYPE
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	public String getActBizType() {
		return actBizType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.ACT_BIZ_TYPE
	 * @param actBizType  the value for YLJZN.JZ_ACT.ACT_BIZ_TYPE
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	public void setActBizType(String actBizType) {
		this.actBizType = actBizType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.ACT_BIZ_TIMES
	 * @return  the value of YLJZN.JZ_ACT.ACT_BIZ_TIMES
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	public Short getActBizTimes() {
		return actBizTimes;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.ACT_BIZ_TIMES
	 * @param actBizTimes  the value for YLJZN.JZ_ACT.ACT_BIZ_TIMES
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	public void setActBizTimes(Short actBizTimes) {
		this.actBizTimes = actBizTimes;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.ACT_BIZ_MONEY
	 * @return  the value of YLJZN.JZ_ACT.ACT_BIZ_MONEY
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	public BigDecimal getActBizMoney() {
		return actBizMoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.ACT_BIZ_MONEY
	 * @param actBizMoney  the value for YLJZN.JZ_ACT.ACT_BIZ_MONEY
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	public void setActBizMoney(BigDecimal actBizMoney) {
		this.actBizMoney = actBizMoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.ACT_BIZ_INHOSPITAL_TIMES
	 * @return  the value of YLJZN.JZ_ACT.ACT_BIZ_INHOSPITAL_TIMES
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	public Short getActBizInhospitalTimes() {
		return actBizInhospitalTimes;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.ACT_BIZ_INHOSPITAL_TIMES
	 * @param actBizInhospitalTimes  the value for YLJZN.JZ_ACT.ACT_BIZ_INHOSPITAL_TIMES
	 * @ibatorgenerated  Wed Jan 13 15:26:19 CST 2010
	 */
	public void setActBizInhospitalTimes(Short actBizInhospitalTimes) {
		this.actBizInhospitalTimes = actBizInhospitalTimes;
	}
}
