package com.medical.model;

import java.util.Date;

public class JzChronicstatus {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_CHRONICSTATUS.CHRONICSTATUS_ID
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	private Long chronicstatusId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_CHRONICSTATUS.FAMILY_ID
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	private String familyId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_CHRONICSTATUS.NAME
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	private String name;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_CHRONICSTATUS.SSN
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	private String ssn;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_CHRONICSTATUS.ENTITY
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	private Integer entity;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_CHRONICSTATUS.STATE
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	private String state;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_CHRONICSTATUS.APPTIME
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	private Date apptime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_CHRONICSTATUS.FLAG
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	private String flag;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_CHRONICSTATUS.MEMBER_ID
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	private String memberId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_CHRONICSTATUS.MEMBER_TYPE
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	private String memberType;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_CHRONICSTATUS.CHRONICSTATUS_ID
	 * @return  the value of YLJZN.JZ_CHRONICSTATUS.CHRONICSTATUS_ID
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public Long getChronicstatusId() {
		return chronicstatusId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_CHRONICSTATUS.CHRONICSTATUS_ID
	 * @param chronicstatusId  the value for YLJZN.JZ_CHRONICSTATUS.CHRONICSTATUS_ID
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public void setChronicstatusId(Long chronicstatusId) {
		this.chronicstatusId = chronicstatusId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_CHRONICSTATUS.FAMILY_ID
	 * @return  the value of YLJZN.JZ_CHRONICSTATUS.FAMILY_ID
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public String getFamilyId() {
		return familyId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_CHRONICSTATUS.FAMILY_ID
	 * @param familyId  the value for YLJZN.JZ_CHRONICSTATUS.FAMILY_ID
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public void setFamilyId(String familyId) {
		this.familyId = familyId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_CHRONICSTATUS.NAME
	 * @return  the value of YLJZN.JZ_CHRONICSTATUS.NAME
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_CHRONICSTATUS.NAME
	 * @param name  the value for YLJZN.JZ_CHRONICSTATUS.NAME
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_CHRONICSTATUS.SSN
	 * @return  the value of YLJZN.JZ_CHRONICSTATUS.SSN
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public String getSsn() {
		return ssn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_CHRONICSTATUS.SSN
	 * @param ssn  the value for YLJZN.JZ_CHRONICSTATUS.SSN
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_CHRONICSTATUS.ENTITY
	 * @return  the value of YLJZN.JZ_CHRONICSTATUS.ENTITY
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public Integer getEntity() {
		return entity;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_CHRONICSTATUS.ENTITY
	 * @param entity  the value for YLJZN.JZ_CHRONICSTATUS.ENTITY
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public void setEntity(Integer entity) {
		this.entity = entity;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_CHRONICSTATUS.STATE
	 * @return  the value of YLJZN.JZ_CHRONICSTATUS.STATE
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_CHRONICSTATUS.STATE
	 * @param state  the value for YLJZN.JZ_CHRONICSTATUS.STATE
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_CHRONICSTATUS.APPTIME
	 * @return  the value of YLJZN.JZ_CHRONICSTATUS.APPTIME
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public Date getApptime() {
		return apptime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_CHRONICSTATUS.APPTIME
	 * @param apptime  the value for YLJZN.JZ_CHRONICSTATUS.APPTIME
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public void setApptime(Date apptime) {
		this.apptime = apptime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_CHRONICSTATUS.FLAG
	 * @return  the value of YLJZN.JZ_CHRONICSTATUS.FLAG
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public String getFlag() {
		return flag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_CHRONICSTATUS.FLAG
	 * @param flag  the value for YLJZN.JZ_CHRONICSTATUS.FLAG
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_CHRONICSTATUS.MEMBER_ID
	 * @return  the value of YLJZN.JZ_CHRONICSTATUS.MEMBER_ID
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public String getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_CHRONICSTATUS.MEMBER_ID
	 * @param memberId  the value for YLJZN.JZ_CHRONICSTATUS.MEMBER_ID
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_CHRONICSTATUS.MEMBER_TYPE
	 * @return  the value of YLJZN.JZ_CHRONICSTATUS.MEMBER_TYPE
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public String getMemberType() {
		return memberType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_CHRONICSTATUS.MEMBER_TYPE
	 * @param memberType  the value for YLJZN.JZ_CHRONICSTATUS.MEMBER_TYPE
	 * @ibatorgenerated  Thu Apr 21 10:53:39 CST 2011
	 */
	public void setMemberType(String memberType) {
		this.memberType = memberType;
	}
}